<script lang="ts" setup>
useHead({
  title: "Quản lý tài khoản",
});

const columns = [
  {
    name: "index",
    label: "STT",
    field: "index",
  },
  {
    name: "name",
    required: true,
    label: "Dessert (100g serving)",
    align: "left",
    field: (row: any) => row.name,
  },
  {
    name: "email",
    align: "left",
    label: "Email",
    field: "email",
  },
  { name: "role", label: "Vai trò (g)", field: "role", sortable: true },
  {
    name: "updated_at",
    label: "Ngày cập nhật",
    field: "updated_at",
  },
  {
    name: "action",
    label: "",
    field: "iron",
  },
];

const rows: any = [
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
  {
    name: "Frozen Yogurt",
    email: 159,
    role: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    updated_at: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    email: 237,
    role: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    updated_at: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    email: 262,
    role: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    updated_at: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    email: 305,
    role: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    updated_at: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    email: 356,
    role: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    updated_at: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    email: 375,
    role: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    updated_at: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    email: 392,
    role: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    updated_at: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    email: 408,
    role: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    updated_at: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    email: 452,
    role: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    updated_at: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    email: 518,
    role: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    updated_at: "12%",
    iron: "6%",
  },
];

const stringOptions = ["Google", "Facebook", "Twitter", "Apple", "Oracle"];
const role = ref(null);
const search = ref(null);

rows.forEach((row: any, index: number) => {
  row.index = index + 1;
});
</script>

<template>
  <div class="account-page flex items-center gap-2">
    <div class="flex flex-row items-center justify-between w-full">
      <div class="q-table__title">Danh sách tài khoản</div>

      <div class="flex items-center gap-1">
        <q-input
          outlined
          v-model="search"
          placeholder="Tìm kiếm tài khoản"
          dense
        >
          <template v-slot:append>
            <q-icon name="eva-search-outline" />
          </template>
        </q-input>

        <q-select
          outlined
          dense
          placeholder="Chọn vai trò"
          :options="stringOptions"
          v-model="role"
        >
        </q-select>
        <q-btn color="primary">Tạo tài khoản</q-btn>
      </div>
    </div>

    <q-table
      :rows="rows"
      :columns="columns"
      virtual-scroll
      style="height: calc(100vh - 134px)"
      class="w-full"
      row-key="name"
      flat
    />
  </div>
</template>
